apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
    - details
  http:
    - fault:
        abort:
          percentage:
            value: 70.0
          httpStatus: 400
      route:
        - destination:
            host: details
            subset: v1