apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
    - details
  http:
    - fault:
        delay:
          percent: 100
          fixedDelay: 5s
      route:
        - destination:
            host: details
            subset: v1